name: startup_app_route_on
description: Butuan Transit MVP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.7
  # The new REAL map packages:
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 900
  assets:
    - assets/Butuan_map.png
    - assets/Tricycle_map.png