// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQaXCW2KxJkq2Srva4Z9Ksl_E-HxQZcY',
    appId: '1:1031672498762:web:edba5562a6c2a8e2b5b4b3',
    messagingSenderId: '1031672498762',
    projectId: 'routeon-d52f7',
    authDomain: 'routeon-d52f7.firebaseapp.com',
    storageBucket: 'routeon-d52f7.firebasestorage.app',
    measurementId: 'G-8GRJHVFRXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHtbR-wrtQAVmDh_oMpe4-4arzDnj427k',
    appId: '1:1031672498762:android:2bec71744ddf64a7b5b4b3',
    messagingSenderId: '1031672498762',
    projectId: 'routeon-d52f7',
    storageBucket: 'routeon-d52f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRWq69GIXmN-1Rz05sx6p1Knk8HpmRWbw',
    appId: '1:1031672498762:ios:d27a11a1703eafc0b5b4b3',
    messagingSenderId: '1031672498762',
    projectId: 'routeon-d52f7',
    storageBucket: 'routeon-d52f7.firebasestorage.app',
    iosBundleId: 'com.example.startupAppRouteOn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRWq69GIXmN-1Rz05sx6p1Knk8HpmRWbw',
    appId: '1:1031672498762:ios:d27a11a1703eafc0b5b4b3',
    messagingSenderId: '1031672498762',
    projectId: 'routeon-d52f7',
    storageBucket: 'routeon-d52f7.firebasestorage.app',
    iosBundleId: 'com.example.startupAppRouteOn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYQaXCW2KxJkq2Srva4Z9Ksl_E-HxQZcY',
    appId: '1:1031672498762:web:ed8c043023f881c2b5b4b3',
    messagingSenderId: '1031672498762',
    projectId: 'routeon-d52f7',
    authDomain: 'routeon-d52f7.firebaseapp.com',
    storageBucket: 'routeon-d52f7.firebasestorage.app',
    measurementId: 'G-1HPEKX8RH1',
  );
}
